
from enum import Enum

class TipoDocumento(Enum):
    FACTURA = "FACTURA"
    GUIA_REMISION = "GUIA_REMISION"
    NOTA_INGRESO = "NOTA_INGRESO"
    NOTA_SALIDA = "NOTA_SALIDA"
    AJUSTE = "AJUSTE"
    DEVOLUCION = "DEVOLUCION"
    TRANSFERENCIA = "TRANSFERENCIA"
    PEDIDO_INTERNO = "PEDIDO_INTERNO"
